#!/usr/bin/env python3
"""Generate Python FFI protocol types from c/interface.c QTS_* declarations.

This mirrors the declaration parsing approach used by scripts/generate.ts.
"""

from __future__ import annotations

import keyword
import re
import sys
from pathlib import Path

DECL_RE = re.compile(r"^([\w()* ]+[\s*]+)(QTS_\w+)(\((.*?)\)) ?{$", re.MULTILINE)
ATTRIBUTE_RE = re.compile(r"^(\w+)\((.+)\)$")

PY_HEADER = """# This file is generated by python/scripts/generate_ffi_protocol.py.
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class QuickJSFFIProtocol(Protocol):
    \"\"\"Low-level sync FFI protocol for QTS_* functions.\"\"\"

    DEBUG: bool
"""


def strip_attributes(ctype: str) -> str:
    text = ctype.strip()
    while True:
        match = ATTRIBUTE_RE.match(text)
        if not match:
            return text
        text = match.group(2).strip()


def ctype_to_python_type(ctype: str, *, for_return: bool = False) -> str:
    normalized = strip_attributes(ctype)
    normalized = re.sub(r"\bconst\b", "", normalized).strip().replace(" ", "")

    if normalized == "void":
        return "None" if for_return else "None"
    if normalized == "bool":
        return "bool"
    if normalized == "double":
        return "float"
    if normalized in {"int", "size_t", "uint16_t", "uint32_t"}:
        return "int"
    if normalized.startswith("enum"):
        return "int"
    if normalized == "char*":
        return "str"
    if "*" in normalized:
        return "int"
    return "int"


def parse_params(param_list_string: str) -> list[tuple[str, str]]:
    if not param_list_string.strip():
        return []
    out: list[tuple[str, str]] = []
    for index, param_string in enumerate(param_list_string.split(",")):
        param_string = param_string.strip()
        match = re.search(r"\b(\w+)$", param_string)
        if match:
            raw_name = match.group(1)
            raw_type = param_string[: match.start()].strip()
        else:
            raw_name = f"arg{index}"
            raw_type = param_string
        name = sanitize_python_name(raw_name, index)
        out.append((name, raw_type))
    return out


def sanitize_python_name(name: str, index: int) -> str:
    candidate = name or f"arg{index}"
    if keyword.iskeyword(candidate):
        candidate = f"{candidate}_"
    return candidate


def build_protocol(interface_source: str) -> str:
    methods: list[str] = []
    for match in DECL_RE.finditer(interface_source):
        return_type, function_name, _, raw_params = match.groups()
        params = parse_params(raw_params)
        py_params = ", ".join(
            f"{param_name}: {ctype_to_python_type(param_ctype)}"
            for param_name, param_ctype in params
        )
        if py_params:
            py_params = ", " + py_params
        py_return = ctype_to_python_type(return_type.strip(), for_return=True)
        methods.append(f"    def {function_name}(self{py_params}) -> {py_return}: ...")

    footer = """

# Alias kept for readability with future async/sync split.
QuickJSSyncFFIProtocol = QuickJSFFIProtocol
""".rstrip()
    return PY_HEADER + "\n" + "\n".join(methods) + "\n" + footer + "\n"


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]
    interface_path = repo_root / "c" / "interface.c"
    output_path = repo_root / "python" / "src" / "quickjs_emscripten" / "_generated_ffi.py"

    if len(sys.argv) >= 2:
        interface_path = Path(sys.argv[1]).resolve()
    if len(sys.argv) >= 3:
        output_path = Path(sys.argv[2]).resolve()

    source = interface_path.read_text(encoding="utf-8")
    rendered = build_protocol(source)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
